[package]
name = "cosm-orc"
version = "1.3.2"
edition = "2021"
authors = ["Harry Hull <harry.hull1@gmail.com>"]

readme = "README.md"
description = "Cosmwasm smart contract orchestration and gas profiling library"
repository = "https://github.com/de-husk/cosm-orc.git"

keywords = ["cosmos", "cosmwasm", "smart-contract", "profiling"]
categories = ["cryptography::cryptocurrencies"]
license = "Apache-2.0"


[dependencies]
thiserror = "1.0.31"
backtrace = "0.3"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
log = "0.4.0"
config = { version = "0.13.1", features = ["yaml"] }

# NOTE: I need to use an older version of cosmrs until I can fix the transitive dependency collision error
cosmrs = { version = "0.7.1", features = ["rpc", "cosmwasm"] }
cosmos-sdk-proto = "0.12.0"
tendermint-rpc = { version = "0.23.7", features= ["http"] }
tokio = { version = "1.20.1", features = ["full"] }
prost = "0.10.4"

[dev-dependencies]
cw20-base = "0.13"
cw20 = "0.13"
