[package]
name = "cosmos-gas-profiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.51"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
